import { Song } from "../core/entities/Song";

export const GENRES = [
  "All",
  "Pop",
  "R&B",
  "Electronic",
  "Hip-Hop",
  "Indie",
  "Lo-fi",
  "Jazz",
];

export const SORT_OPTIONS = [
  { value: "default", label: "Default" },
  { value: "title", label: "Title A–Z" },
  { value: "artist", label: "Artist" },
  { value: "duration", label: "Duration" },
  { value: "liked", label: "Liked First" },
];

export const INITIAL_SONGS: Song[] = [
  {
    id: "1",
    path: "",
    title: "Daydream",
    artist: "Lauv",
    album: "I met you when I was 18.",
    duration: 224,
    genre: "Pop",
    year: null,
    track_number: null,
    artwork: null,
    dur: "3:44",
    emoji: "🌙",
    grad: "linear-gradient(135deg,#2d1f6e,#0f172a)",
    bpm: 118,
    key: "A♭ maj",
    plays: 284,
    liked: true,
  },
  {
    id: "2",
    path: "",
    title: "I Like Me Better",
    artist: "Lauv",
    album: "I met you when I was 18.",
    duration: 202,
    genre: "Pop",
    year: null,
    track_number: null,
    artwork: null,
    dur: "3:22",
    emoji: "💜",
    grad: "linear-gradient(135deg,#4c1d95,#1e1b4b)",
    bpm: 112,
    key: "C maj",
    plays: 521,
    liked: true,
  },
  {
    id: "3",
    path: "",
    title: "Paris in the Rain",
    artist: "Lauv",
    album: "How I'm Feeling",
    duration: 192,
    genre: "Pop",
    year: null,
    track_number: null,
    artwork: null,
    dur: "3:12",
    emoji: "🌧️",
    grad: "linear-gradient(135deg,#0c4a6e,#0f172a)",
    bpm: 95,
    key: "D maj",
    plays: 198,
    liked: false,
  },
  {
    id: "4",
    path: "",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    duration: 200,
    genre: "Pop",
    year: null,
    track_number: null,
    artwork: null,
    dur: "3:20",
    emoji: "🌃",
    grad: "linear-gradient(135deg,#7f1d1d,#0f172a)",
    bpm: 171,
    key: "F♯ min",
    plays: 612,
    liked: true,
  },
  {
    id: "5",
    path: "",
    title: "Midnight Rain",
    artist: "Taylor Swift",
    album: "Midnights",
    duration: 213,
    genre: "Pop",
    year: null,
    track_number: null,
    artwork: null,
    dur: "3:33",
    emoji: "🌂",
    grad: "linear-gradient(135deg,#1e3a5f,#0c1628)",
    bpm: 107,
    key: "B min",
    plays: 342,
    liked: false,
  },
  {
    id: "6",
    path: "",
    title: "Starboy",
    artist: "The Weeknd",
    album: "Starboy",
    duration: 230,
    genre: "R&B",
    year: null,
    track_number: null,
    artwork: null,
    dur: "3:50",
    emoji: "⭐",
    grad: "linear-gradient(135deg,#451a03,#1c0a00)",
    bpm: 185,
    key: "D♭ maj",
    plays: 488,
    liked: true,
  },
  {
    id: "7",
    path: "",
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: 203,
    genre: "Pop",
    year: null,
    track_number: null,
    artwork: null,
    dur: "3:23",
    emoji: "🚀",
    grad: "linear-gradient(135deg,#4a044e,#1a0020)",
    bpm: 103,
    key: "B maj",
    plays: 391,
    liked: false,
  },
  {
    id: "8",
    path: "",
    title: "As It Was",
    artist: "Harry Styles",
    album: "Harry's House",
    duration: 157,
    genre: "Pop",
    year: null,
    track_number: null,
    artwork: null,
    dur: "2:37",
    emoji: "🌸",
    grad: "linear-gradient(135deg,#831843,#1a0010)",
    bpm: 174,
    key: "A maj",
    plays: 266,
    liked: true,
  },
  {
    id: "9",
    path: "",
    title: "good 4 u",
    artist: "Olivia Rodrigo",
    album: "SOUR",
    duration: 178,
    genre: "Pop",
    year: null,
    track_number: null,
    artwork: null,
    dur: "2:58",
    emoji: "💢",
    grad: "linear-gradient(135deg,#7c2d12,#0f172a)",
    bpm: 166,
    key: "A maj",
    plays: 177,
    liked: false,
  },
  {
    id: "10",
    path: "",
    title: "Peaches",
    artist: "Justin Bieber",
    album: "Justice",
    duration: 198,
    genre: "R&B",
    year: null,
    track_number: null,
    artwork: null,
    dur: "3:18",
    emoji: "🍑",
    grad: "linear-gradient(135deg,#78350f,#1c0a00)",
    bpm: 90,
    key: "C♯ maj",
    plays: 203,
    liked: false,
  },
  {
    id: "11",
    path: "",
    title: "Heat Waves",
    artist: "Glass Animals",
    album: "Dreamland",
    duration: 239,
    genre: "Indie",
    year: null,
    track_number: null,
    artwork: null,
    dur: "3:59",
    emoji: "🔥",
    grad: "linear-gradient(135deg,#7c2d12,#431407)",
    bpm: 80,
    key: "D min",
    plays: 328,
    liked: true,
  },
  {
    id: "12",
    path: "",
    title: "Industry Baby",
    artist: "Lil Nas X",
    album: "Montero",
    duration: 212,
    genre: "Hip-Hop",
    year: null,
    track_number: null,
    artwork: null,
    dur: "3:32",
    emoji: "🎺",
    grad: "linear-gradient(135deg,#1e3a5f,#0f0a1e)",
    bpm: 150,
    key: "F min",
    plays: 441,
    liked: false,
  },
  {
    id: "13",
    path: "",
    title: "Redbone",
    artist: "Childish Gambino",
    album: "Awaken, My Love!",
    duration: 326,
    genre: "R&B",
    year: null,
    track_number: null,
    artwork: null,
    dur: "5:26",
    emoji: "🎸",
    grad: "linear-gradient(135deg,#3b0764,#0f0a1e)",
    bpm: 96,
    key: "D♭ maj",
    plays: 159,
    liked: true,
  },
  {
    id: "14",
    path: "",
    title: "Night Dancer",
    artist: "imase",
    album: "Night Dancer",
    duration: 183,
    genre: "Pop",
    year: null,
    track_number: null,
    artwork: null,
    dur: "3:03",
    emoji: "💃",
    grad: "linear-gradient(135deg,#0f4c75,#0f172a)",
    bpm: 128,
    key: "A min",
    plays: 287,
    liked: true,
  },
  {
    id: "15",
    path: "",
    title: "Ocean Eyes",
    artist: "Billie Eilish",
    album: "Don't Smile at Me",
    duration: 200,
    genre: "Pop",
    year: null,
    track_number: null,
    artwork: null,
    dur: "3:20",
    emoji: "👁️",
    grad: "linear-gradient(135deg,#0c4a6e,#0f172a)",
    bpm: 84,
    key: "G maj",
    plays: 319,
    liked: false,
  },
  {
    id: "16",
    path: "",
    title: "Circles",
    artist: "Post Malone",
    album: "Hollywood's Bleeding",
    duration: 215,
    genre: "Pop",
    year: null,
    track_number: null,
    artwork: null,
    dur: "3:35",
    emoji: "🔄",
    grad: "linear-gradient(135deg,#134e4a,#0f172a)",
    bpm: 120,
    key: "B♭ maj",
    plays: 372,
    liked: true,
  },
  {
    id: "17",
    path: "",
    title: "coffee",
    artist: "beabadoobee",
    album: "Fake It Flowers",
    duration: 143,
    genre: "Indie",
    year: null,
    track_number: null,
    artwork: null,
    dur: "2:23",
    emoji: "☕",
    grad: "linear-gradient(135deg,#292524,#0a0a0a)",
    bpm: 92,
    key: "G♯ maj",
    plays: 144,
    liked: true,
  },
  {
    id: "18",
    path: "",
    title: "Lofi Study Beat",
    artist: "ChillHop",
    album: "Café Sessions",
    duration: 252,
    genre: "Lo-fi",
    year: null,
    track_number: null,
    artwork: null,
    dur: "4:12",
    emoji: "📚",
    grad: "linear-gradient(135deg,#1a2e05,#0f172a)",
    bpm: 75,
    key: "F maj",
    plays: 89,
    liked: false,
  },
  {
    id: "19",
    path: "",
    title: "So What",
    artist: "Miles Davis",
    album: "Kind of Blue",
    duration: 562,
    genre: "Jazz",
    year: null,
    track_number: null,
    artwork: null,
    dur: "9:22",
    emoji: "🎷",
    grad: "linear-gradient(135deg,#1e1b4b,#0f0a1e)",
    bpm: 60,
    key: "G min",
    plays: 67,
    liked: true,
  },
  {
    id: "20",
    path: "",
    title: "Breathe (feat. Lauv)",
    artist: "Lauv",
    album: "How I'm Feeling",
    duration: 169,
    genre: "Electronic",
    year: null,
    track_number: null,
    artwork: null,
    dur: "2:49",
    emoji: "💨",
    grad: "linear-gradient(135deg,#2d1f6e,#0f172a)",
    bpm: 130,
    key: "E min",
    plays: 211,
    liked: false,
  },
];
